version: '3'

services:
  git:
    image: alpine/git:latest
    container_name: GIT

  bot:
    container_name: PINK_BOT
    restart: always
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    depends_on:
      - db
    links:
      - db

  db:
    image: 'mongo'
    container_name: PINK_BOT_BRAIN
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db